[env:leaf_wifi24]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 230400
upload_speed = 921600
build_flags =
    -DLEAF_VERSION=\"1.3.0\"
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DMAX_LINE_LEN=200
    -DHB_INTERVAL_MS=10000
    -DCONFIG_TIMEOUT_MS=10000
    -DSCAN_FAIL_RESET_THRESHOLD=10
    -DSCAN_FAIL_REBOOT_THRESHOLD=50
    -DHEAP_MIN_BYTES=16384
    -DWIDS_RING_SIZE=64
    -DWIDS_SEEN_BSSID_MAX=512
    -DCORE_DEBUG_LEVEL=0
