[env:leaf_ble]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 230400
build_flags =
    -DLEAF_VERSION=\"1.0.0\"
    -DLEAF_KIND_BLE=1
    -DMAX_LINE_LEN=200
    -DHB_INTERVAL_MS=10000
    -DCONFIG_TIMEOUT_MS=10000
    -DBLE_DEDUP_WINDOW_MS=1000
    -DBLE_RING_SIZE=32
